# Generated by Django 3.0.4 on 2020-03-31 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default='', max_length=200, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=200)),
                ('product_price', models.FloatField(default=0.0)),
                ('purchased', models.BooleanField(default=False)),
                ('receivers', models.CharField(default='', max_length=500)),
                ('shared_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_list.SharedList')),
            ],
        ),
    ]
