# Generated by Django 3.0.4 on 2020-03-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_list', '0002_auto_20200326_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedlist',
            name='user',
        ),
        migrations.AddField(
            model_name='sharedlist',
            name='group_id',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
