# Generated by Django 3.0.4 on 2020-03-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_list', '0003_auto_20200326_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
