# Generated by Django 3.0.4 on 2020-03-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='debt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_grouped',
            field=models.BooleanField(default=False),
        ),
    ]
